# Site settings
title: Welcome to My Blog!
header-img: img/home-bg.png
email: dlyn1110@gmail.com
copyright_name: dlyn1110
description: > # this means to ignore newlines until "baseurl:"
  Keep Calm and Code!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dlyn1110
learn_profile: dlyn1110
email_username: dlyn1110@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
